### ISSUE TITLE
Validate  or Normalize typo in contracts addresses for subgraph.yaml

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-cli#166]
See Code: 

```
specVersion: 0.0.1
schema:
  file: ./schema.graphql
dataSources:
- kind: ethereum/contract
  name: DAOFactory
  source:
    address: " 0x595B34C93aA2c2ba0A38daEEdE629a0DfBDcc559" # Mainnet: 0x595B34C93aA2c2ba0A38daEEdE629a0DfBDcc559
    abi: DAOFactory
```

That extra space in the contract address is allowable, and the subgraph gets created, but then a weird error appears: `Error deploying the subgraph: subgraph resolve error: parse error: Invalid character 'x' at position 2`. This error message is really unclear so we should fix this.

We should normalize the contract address or else validate it ahead of time. Validating is probably good enough.
