### ISSUE TITLE
Error deploying the subgraph: Internal error: Could not pick index node

### ISSUE THREAD

**Issue by felipecespedes** [graphprotocol/graph-cli#204]
I'm trying to use rinkeby as a network but I'm getting the following error
"Error deploying the subgraph: Internal error: Could not pick index node"

This is my `subgraph.yaml` file

```yaml
specVersion: 0.0.1
description: A simple counter
repository: https://github.com/graphprotocol/example-subgraph
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: Counter
    network: rinkeby
    source:
      address: '0x45f63f232ad2f3b5cdeb48cefc9da7358819a642'
      abi: Counter
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.1
      language: wasm/assemblyscript
      entities:
        - Counter
      abis:
        - name: Counter
          file: ./abis/Counter.abi
      eventHandlers:
        - event: Incremented(uint256)
          handler: handleIncremented
      file: ./src/mapping.ts

```

this a fresh project, I've only changed the `network` and `address` properties, the contract is already deployed in that address.

any ideas?
