### ISSUE TITLE
Incorrect Tuple Fields generated

### ISSUE THREAD

**Issue by samparsky** [graphprotocol/graph-cli#500]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
CallHandlers doesn't work with tuple arguments. A call handler for a function with tuple arguments doesn't get invoked

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

```js
contract Test {
  struct Check {
     uint param;
  }
  function test(Check memory check) {
    
  }
}
```

`subgraph.yaml`

```yml
specVersion: 0.0.2
description: AdEx Protocol subgraph
schema:
  file: ./schema.graphql

dataSources:
  ...
  callHandlers:
        - function: test(tuple)
          handler: handleTest
```

The `handleTest` handler doesn't ever get invoked

According to the issue I opened here https://github.com/graphprotocol/graph-node/issues/1668 the manifest should look like
```js
callHandlers:
  - function: test((uint256))
    handler: handleTest
```

But when I tried it `graph-cli` gives the error below

The error from `yarn build` 
```sh
 Call function with signature 'test((uint256))' not present in ABI 'Test'.
  Available call functions:
  - test(tuple)
```

**What is the expected behavior?**

The handleTest handler should get invoked
