### ISSUE TITLE
Error: Deploy subgraph on  bsc

### ISSUE THREAD

**Issue by tdergouzi** [graphprotocol/graph-cli#641]
HTTP error deploying the subgraph 502
error Command failed with exit code 1.
```yaml
specVersion: 0.0.2
description: Gravatar for Ethereum
repository: https://github.com/graphprotocol/example-subgraph
schema:
  file: ./schema.graphql
dataSources:
  #    factory contract
  - kind: ethereum/contract
    name: Factory
    network: bsc
    source:
      address: '0x8a1E9d3aEbBBd5bA2A64d3355A48dD5E9b511256'
      abi: Factory
      startBlock: 601290
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.4
      language: wasm/assemblyscript
      entities:
        - Factory
      abis:
        - name: Factory
          file: ./build/contracts/Factory.json
        - name: ERC20
          file: ./build/contracts/ERC20.json
        - name: Config
          file: ./build/contracts/Config.json
      eventHandlers:
        - event: PairCreated(indexed address,indexed address,address,uint256)
          handler: handleNewPair
      file: ./src/factory.ts
```
