### ISSUE TITLE
graph test does not work with yarn pnp linker

### ISSUE THREAD

**Issue by tuler** [graphprotocol/graph-cli#815]
First of all it looks like there is a missing dependency to `strip-ansi`.
I had to configure this in my `.yarnrc.yaml`

```yaml
packageExtensions:
    "@graphprotocol/graph-cli@*":
        dependencies:
            "strip-ansi": "5.2.0"
```

Then when running `graph test` I get this error:

```
EROFS: read-only filesystem, mkdir '/node_modules/binary-install-raw/bin
```

It looks like graph is trying to download binaries (for matchstick?) to `node_modules` but this directory does not exist anymore for yarn modern pnp linker.
