### ISSUE TITLE
IPFS hash is different

### ISSUE THREAD

**Issue by air3ijai** [graphprotocol/graph-cli#898]
Hello,

As [graph-cli](https://github.com/graphprotocol/graph-cli) doest support [HTTP headers or basic authentication](880) we need an alternative, we use it just for the build.

 1. `yarn graph build` --> ./build
 2. [ipfs-action](https://github.com/aquiladev/ipfs-action) <-- ./build
 3. `yarn graph build --ipfs http://domain.tld` - just to compare result
 4. `ipfs add -r ./build`

```
ipfs-action             - Qmf7xitufZaFLwZzUC3bFBU98yhnRpSSwSwuNB6EHWEuZg
yarn graph build --ipfs - QmQRwfFmr5N85eSKCFGBqAqVmvCHxikqgtdt3KXpQcboPF
ipfs add -r             - Qmf7xitufZaFLwZzUC3bFBU98yhnRpSSwSwuNB6EHWEuZg
```

Why do we have different results in case of graph-cli comparing to the ipfs-action and go-ipfs local add?

**ipfs-action**
```
Upload to IPFS finished successfully {
  cid: 'Qmf7xitufZaFLwZzUC3bFBU98yhnRpSSwSwuNB6EHWEuZg',
  ipfs: 'Qmf7xitufZaFLwZzUC3bFBU98yhnRpSSwSwuNB6EHWEuZg',
  ipns: undefined
}
```
**yarn graph build --ipfs**
```
✔ Write compiled subgraph to build/
  Add file to IPFS build/schema.graphql
                .. Qmc5tCgYN68BMfk5EUvSnS21FawKKiHYYC6JVdKP6uNkaP
  Add file to IPFS build/Factory/abis/BFactory.json
                .. QmRoFgJHxz8BjcSPDCwDe2K7PGwS1N7mnsBw6ZNdbMzwHK
  Add file to IPFS build/DTFactory/abis/DTFactory.json
                .. QmZGNpmjeNo8DojMd3DGf8h8LNB6MaEvpt2cwYVXfYxSaF
  Add file to IPFS build/Metadata/abis/Metadata.json
                .. QmVpHWFbvqrS5Qj9x4SBBZG3g2WvLpFQZhgpViKfgg24Gv
  Add file to IPFS build/FixedRateExchange/abis/FixedRateExchange.json
                .. QmUHeEcp2VtURsDADbk2NSXvC5F9iaBLY4SSJMcK8TriYt
  Add file to IPFS build/FixedRateExchange/abis/ERC20.json
                .. QmXuTbDkNrN27VydxbS2huvKRk62PMgUTdPDWkxcr2w7j2
  Add file to IPFS build/FixedRateExchange/abis/ERC20SymbolBytes.json
                .. QmbHnhUFZa6qqqRyubUYhXntox1TCBxqryaBM1iNGqVJzT
  Add file to IPFS build/FixedRateExchange/abis/ERC20NameBytes.json
                .. QmQCP6Pdp1MqpwRv2qoPHuUTwZGy7Q3eDHg4w5kzwE9mBj
  Add file to IPFS build/Dispenser/abis/Dispenser.json
                .. QmbALakSJU62ZAeEfL83Xwr5tdp9W7L9Nf5arsTUWAXPkC
  Add file to IPFS build/Factory/Factory.wasm
                .. QmRuagqUWVmsmdynevcYQPzc9QMN82qDHHtpF1nfZTPvbq
  Add file to IPFS build/DTFactory/DTFactory.wasm
                .. QmcgWpf9Umt1o5YmcxPbSENWpoL8WjBEboKYYpnju1cAL9
  Add file to IPFS build/Metadata/Metadata.wasm
                .. QmRmFLHV1kBCkhcGip2MmS8J6aPeJyxLFDHXTeYpxpPV2A
  Add file to IPFS build/FixedRateExchange/FixedRateExchange.wasm
                .. QmeZypygKDCPULGdXmr7ogKeNjniZmmQ9m7qzWzppjsDG4
  Add file to IPFS build/Dispenser/Dispenser.wasm
                .. QmWnSAHutUkHTus7uExCTb6FzCMQWMAupbiteMPic1wqzz
  Add file to IPFS build/Pool/abis/BPool.json
                .. QmZ7j6kaQs3tfTjWXAVmBDtR3QTwvVDx9ydngdZgEcwL7R
  Add file to IPFS build/Pool/abis/BToken.json
                .. QmVynyRtcPAuKA9zgjKaCv9rX8KxozwhJ5DGbBCGDR62hp
  Add file to IPFS build/Pool/abis/ERC20.json
                .. QmXuTbDkNrN27VydxbS2huvKRk62PMgUTdPDWkxcr2w7j2 (already uploaded)
  Add file to IPFS build/Pool/abis/ERC20SymbolBytes.json
                .. QmbHnhUFZa6qqqRyubUYhXntox1TCBxqryaBM1iNGqVJzT (already uploaded)
  Add file to IPFS build/Pool/abis/ERC20NameBytes.json
                .. QmQCP6Pdp1MqpwRv2qoPHuUTwZGy7Q3eDHg4w5kzwE9mBj (already uploaded)
  Add file to IPFS build/templates/Pool/Pool.wasm
                .. QmRpuRtWKVF7Hp6auTkCnccQu8B83dgsEbwNrjFGMwGmJ5
  Add file to IPFS build/DataToken/abis/DataTokenTemplate.json
                .. QmSdM7LmKJmQWQ1hB8cRpRHzSX5y9pJ4gLzn96cRwHGsHS
  Add file to IPFS build/templates/DataToken/DataToken.wasm
                .. QmTdnukhWti63JtbTzZH1NQbLLunuvEgC2vMRRfqWeaNxZ
✔ Upload subgraph to IPFS

Build completed: QmQRwfFmr5N85eSKCFGBqAqVmvCHxikqgtdt3KXpQcboPF
```

**ipfs add -r**
```
added QmcgWpf9Umt1o5YmcxPbSENWpoL8WjBEboKYYpnju1cAL9 build/DTFactory/DTFactory.wasm
added QmZGNpmjeNo8DojMd3DGf8h8LNB6MaEvpt2cwYVXfYxSaF build/DTFactory/abis/DTFactory.json
added QmSdM7LmKJmQWQ1hB8cRpRHzSX5y9pJ4gLzn96cRwHGsHS build/DataToken/abis/DataTokenTemplate.json
added QmWnSAHutUkHTus7uExCTb6FzCMQWMAupbiteMPic1wqzz build/Dispenser/Dispenser.wasm
added QmbALakSJU62ZAeEfL83Xwr5tdp9W7L9Nf5arsTUWAXPkC build/Dispenser/abis/Dispenser.json
added QmRuagqUWVmsmdynevcYQPzc9QMN82qDHHtpF1nfZTPvbq build/Factory/Factory.wasm
added QmRoFgJHxz8BjcSPDCwDe2K7PGwS1N7mnsBw6ZNdbMzwHK build/Factory/abis/BFactory.json
added QmeZypygKDCPULGdXmr7ogKeNjniZmmQ9m7qzWzppjsDG4 build/FixedRateExchange/FixedRateExchange.wasm
added QmXuTbDkNrN27VydxbS2huvKRk62PMgUTdPDWkxcr2w7j2 build/FixedRateExchange/abis/ERC20.json
added QmQCP6Pdp1MqpwRv2qoPHuUTwZGy7Q3eDHg4w5kzwE9mBj build/FixedRateExchange/abis/ERC20NameBytes.json
added QmbHnhUFZa6qqqRyubUYhXntox1TCBxqryaBM1iNGqVJzT build/FixedRateExchange/abis/ERC20SymbolBytes.json
added QmUHeEcp2VtURsDADbk2NSXvC5F9iaBLY4SSJMcK8TriYt build/FixedRateExchange/abis/FixedRateExchange.json
added QmRmFLHV1kBCkhcGip2MmS8J6aPeJyxLFDHXTeYpxpPV2A build/Metadata/Metadata.wasm
added QmVpHWFbvqrS5Qj9x4SBBZG3g2WvLpFQZhgpViKfgg24Gv build/Metadata/abis/Metadata.json
added QmZ7j6kaQs3tfTjWXAVmBDtR3QTwvVDx9ydngdZgEcwL7R build/Pool/abis/BPool.json
added QmVynyRtcPAuKA9zgjKaCv9rX8KxozwhJ5DGbBCGDR62hp build/Pool/abis/BToken.json
added QmXuTbDkNrN27VydxbS2huvKRk62PMgUTdPDWkxcr2w7j2 build/Pool/abis/ERC20.json
added QmQCP6Pdp1MqpwRv2qoPHuUTwZGy7Q3eDHg4w5kzwE9mBj build/Pool/abis/ERC20NameBytes.json
added QmbHnhUFZa6qqqRyubUYhXntox1TCBxqryaBM1iNGqVJzT build/Pool/abis/ERC20SymbolBytes.json
added Qmc5tCgYN68BMfk5EUvSnS21FawKKiHYYC6JVdKP6uNkaP build/schema.graphql
added QmXSK8D3BNMi2Q6XY7xAYw5Ke334pPjgWKAS1i9qNeoqnU build/subgraph.yaml
added QmTdnukhWti63JtbTzZH1NQbLLunuvEgC2vMRRfqWeaNxZ build/templates/DataToken/DataToken.wasm
added QmRpuRtWKVF7Hp6auTkCnccQu8B83dgsEbwNrjFGMwGmJ5 build/templates/Pool/Pool.wasm
added Qmeae3QCDnGoWPjvxWGGXxghvCbsp2jVZkw2WwDLahYRCP build/DTFactory/abis
added QmTRjmuJk7f5jx4NCXaYVmeanppk673GTFutsa7T3FJV7U build/DTFactory
added QmYck7idf19nasjtDnuK5YYd3U1QL4vVZZt19LLTyZsRky build/DataToken/abis
added QmTGJQA7gZoDjbFyuhat42F4RJcce32YgT5k2Q4Zm9p3p7 build/DataToken
added QmesYcp8gvn6S5mfdTHJk47ApbUFPecfTwfL5NyVidgggd build/Dispenser/abis
added QmYAfx85PJUrwQaF6rynbyGStHBFeSfPB8zMryGFPSkGB5 build/Dispenser
added QmaRHqC11oa1NMkQLfqTSr2A5pCvLz1sQDJkGu6965eJ7C build/Factory/abis
added Qmf7XzYpYt299KpDTsfJPoeAYKiMaeSa2KAymjhk7ytCXJ build/Factory
added QmdPsNbqRcCQ7Q3ahEUM65aiszVqWN6gvTnSr2S2MCkMpf build/FixedRateExchange/abis
added QmUhKK2vhQrrCZKAfSDoJdTGavjDnBZrGAzwttA1oC7UCm build/FixedRateExchange
added QmdJiTCSKFBAzD5bEtMXcnNmkjXSmjyiiuFbCmAGbRJWJo build/Metadata/abis
added Qmf3mY4fgTBLcsfWQtuE8rmP9udeLN7FGYyz1rxeFbVtaS build/Metadata
added QmXJSn4FHivAcxGL263umVvKSftc9VCweUQJxm6Xx6dYmh build/Pool/abis
added QmaankWLyiG67cCqNXz5VsxP1ihWVvZuVMgtcepJrHqmSt build/Pool
added QmNr3u3g5zY2N26txXfrwiaUcrZihdrUyADUBCYjNHsGE5 build/templates/DataToken
added QmZF6uxt5irwQmSFQNagic2zdq1meXEmacAZ3hNVbZJRif build/templates/Pool
added QmNWeuXVK7Mkk6AwX6S4SYeL6RkgyKAVQMpQW9iMBmrSA4 build/templates
added Qmf7xitufZaFLwZzUC3bFBU98yhnRpSSwSwuNB6EHWEuZg build
```

**Comment by air3ijai** [comment]
But looks like hash `Qmf7xitufZaFLwZzUC3bFBU98yhnRpSSwSwuNB6EHWEuZg` we got using `ipfs-action` and `ipfs add` points to the folder
```bash
# ipfs cat Qmf7xitufZaFLwZzUC3bFBU98yhnRpSSwSwuNB6EHWEuZg
Error: this dag node is a directory
```

What is the IPFS hash graph-cli is referring to?
```bash
Build completed: QmQRwfFmr5N85eSKCFGBqAqVmvCHxikqgtdt3KXpQcboPF
```

**Comment by air3ijai** [comment]
`QmQRwfFmr5N85eSKCFGBqAqVmvCHxikqgtdt3KXpQcboPF` hash is related to the file which we can't find on the local system

It is created somehow at the end of the upload and also uploaded to the IPFS?
How can we build it and upload to the IPFS manually?


```yaml
dataSources:
  - kind: ethereum/contract
    mapping:
      abis:
        - file:
            /: /ipfs/QmRoFgJHxz8BjcSPDCwDe2K7PGwS1N7mnsBw6ZNdbMzwHK
          name: Factory
      apiVersion: 0.0.4
      entities:
        - PoolFactory
      eventHandlers:
        - event: 'BPoolRegistered(address,indexed address)'
          handler: handleNewPool
      file:
        /: /ipfs/QmRuagqUWVmsmdynevcYQPzc9QMN82qDHHtpF1nfZTPvbq
      kind: ethereum/events
      language: wasm/assemblyscript
    name: Factory
    network: mainnet
    source:
      abi: Factory
      address: '0xbe0083053744ECb871510C88dC0f6b77Da162706'
      startBlock: 14860974
  - kind: ethereum/contract
    mapping:
      abis:
        - file:
            /: /ipfs/QmZGNpmjeNo8DojMd3DGf8h8LNB6MaEvpt2cwYVXfYxSaF
          name: DTFactory
      apiVersion: 0.0.4
      entities:
        - DatatokenFactory
      eventHandlers:
        - event: >-
            TokenRegistered(indexed address,string,string,uint256,indexed
            address,indexed string)
          handler: handleNewToken
      file:
        /: /ipfs/QmcgWpf9Umt1o5YmcxPbSENWpoL8WjBEboKYYpnju1cAL9
      kind: ethereum/events
      language: wasm/assemblyscript
    name: DTFactory
    network: mainnet
    source:
      abi: DTFactory
      address: '0x57317f97E9EA49eBd19f7c9bB7c180b8cDcbDeB9'
      startBlock: 14860974
  - kind: ethereum/contract
    mapping:
      abis:
        - file:
            /: /ipfs/QmVpHWFbvqrS5Qj9x4SBBZG3g2WvLpFQZhgpViKfgg24Gv
          name: Metadata
      apiVersion: 0.0.4
      entities:
        - Metadata
      eventHandlers:
        - event: 'MetadataCreated(indexed address,indexed address,bytes,bytes)'
          handler: handleMetadataCreated
        - event: 'MetadataUpdated(indexed address,indexed address,bytes,bytes)'
          handler: handleMetadataUpdated
      file:
        /: /ipfs/QmRmFLHV1kBCkhcGip2MmS8J6aPeJyxLFDHXTeYpxpPV2A
      kind: ethereum/events
      language: wasm/assemblyscript
    name: Metadata
    network: mainnet
    source:
      abi: Metadata
      address: '0x1a4b70d8c9DcA47cD6D0Fb3c52BB8634CA1C0Fdf'
      startBlock: 14860974
  - kind: ethereum/contract
    mapping:
      abis:
        - file:
            /: /ipfs/QmUHeEcp2VtURsDADbk2NSXvC5F9iaBLY4SSJMcK8TriYt
          name: FixedRateExchange
        - file:
            /: /ipfs/QmXuTbDkNrN27VydxbS2huvKRk62PMgUTdPDWkxcr2w7j2
          name: ERC20
        - file:
            /: /ipfs/QmbHnhUFZa6qqqRyubUYhXntox1TCBxqryaBM1iNGqVJzT
          name: ERC20SymbolBytes
        - file:
            /: /ipfs/QmQCP6Pdp1MqpwRv2qoPHuUTwZGy7Q3eDHg4w5kzwE9mBj
          name: ERC20NameBytes
      apiVersion: 0.0.4
      entities:
        - FixedRateExchange
      eventHandlers:
        - event: >-
            ExchangeCreated(indexed bytes32,indexed address,indexed
            address,address,uint256)
          handler: handleExchangeCreated
        - event: 'ExchangeActivated(indexed bytes32,indexed address)'
          handler: handleExchangeActivated
        - event: 'ExchangeDeactivated(indexed bytes32,indexed address)'
          handler: handleExchangeDeactivated
        - event: 'ExchangeRateChanged(indexed bytes32,indexed address,uint256)'
          handler: handleExchangeRateChanged
        - event: 'Swapped(indexed bytes32,indexed address,uint256,uint256)'
          handler: handleSwapped
      file:
        /: /ipfs/QmeZypygKDCPULGdXmr7ogKeNjniZmmQ9m7qzWzppjsDG4
      kind: ethereum/events
      language: wasm/assemblyscript
    name: FixedRateExchange
    network: mainnet
    source:
      abi: FixedRateExchange
      address: '0x608d05214E42722B94a54cF6114d4840FCfF84e1'
      startBlock: 14860974
  - kind: ethereum/contract
    mapping:
      abis:
        - file:
            /: /ipfs/QmbALakSJU62ZAeEfL83Xwr5tdp9W7L9Nf5arsTUWAXPkC
          name: Dispenser
      apiVersion: 0.0.4
      entities:
        - Dispenser
      eventHandlers:
        - event: Activated(indexed address)
          handler: handleDispenserActivated
        - event: Deactivated(indexed address)
          handler: handleDispenserDeactivated
        - event: AcceptedMinter(indexed address)
          handler: handleDispenserAcceptedMinter
        - event: RemovedMinter(indexed address)
          handler: handleDispenserRemovedMinter
        - event: 'TokensDispensed(indexed address,indexed address,uint256)'
          handler: handleDispenserTokensDispensed
        - event: 'OwnerWithdrawed(indexed address,indexed address,uint256)'
          handler: handleDispenserOwnerWithdrawed
      file:
        /: /ipfs/QmWnSAHutUkHTus7uExCTb6FzCMQWMAupbiteMPic1wqzz
      kind: ethereum/events
      language: wasm/assemblyscript
    name: Dispenser
    network: mainnet
    source:
      abi: Dispenser
      address: '0xDEfD0018969cd2d4E648209F876ADe184815f038'
      startBlock: 14860974
description: Ocean provides data sharing through IDOs
repository: 'https://github.com/oceanprotocol/ocean-subgraph'
schema:
  file:
    /: /ipfs/Qmc5tCgYN68BMfk5EUvSnS21FawKKiHYYC6JVdKP6uNkaP
specVersion: 0.0.2
templates:
  - kind: ethereum/contract
    mapping:
      abis:
        - file:
            /: /ipfs/QmZ7j6kaQs3tfTjWXAVmBDtR3QTwvVDx9ydngdZgEcwL7R
          name: Pool
        - file:
            /: /ipfs/QmVynyRtcPAuKA9zgjKaCv9rX8KxozwhJ5DGbBCGDR62hp
          name: BToken
        - file:
            /: /ipfs/QmXuTbDkNrN27VydxbS2huvKRk62PMgUTdPDWkxcr2w7j2
          name: ERC20
        - file:
            /: /ipfs/QmbHnhUFZa6qqqRyubUYhXntox1TCBxqryaBM1iNGqVJzT
          name: ERC20SymbolBytes
        - file:
            /: /ipfs/QmQCP6Pdp1MqpwRv2qoPHuUTwZGy7Q3eDHg4w5kzwE9mBj
          name: ERC20NameBytes
      apiVersion: 0.0.4
      entities:
        - Pool
        - PoolFactory
        - Swap
      eventHandlers:
        - event: 'LOG_CALL(indexed bytes4,indexed address,bytes)'
          handler: handleSetSwapFee
          topic0: '0x34e1990700000000000000000000000000000000000000000000000000000000'
        - event: 'LOG_CALL(indexed bytes4,indexed address,bytes)'
          handler: handleSetController
          topic0: '0x92eefe9b00000000000000000000000000000000000000000000000000000000'
        - event: 'LOG_CALL(indexed bytes4,indexed address,bytes)'
          handler: handleSetPublicSwap
          topic0: '0x49b5955200000000000000000000000000000000000000000000000000000000'
        - event: 'LOG_CALL(indexed bytes4,indexed address,bytes)'
          handler: handleFinalize
          topic0: '0x4bb278f300000000000000000000000000000000000000000000000000000000'
        - event: 'LOG_CALL(indexed bytes4,indexed address,bytes)'
          handler: handleSetup
          topic0: '0xd1d7bc9100000000000000000000000000000000000000000000000000000000'
        - event: 'LOG_CALL(indexed bytes4,indexed address,bytes)'
          handler: handleRebind
          topic0: '0x3fdddaa200000000000000000000000000000000000000000000000000000000'
        - event: 'LOG_CALL(indexed bytes4,indexed address,bytes)'
          handler: handleRebind
          topic0: '0xe4e1e53800000000000000000000000000000000000000000000000000000000'
        - event: 'LOG_CALL(indexed bytes4,indexed address,bytes)'
          handler: handleGulp
          topic0: '0x8c28cbe800000000000000000000000000000000000000000000000000000000'
        - event: 'LOG_JOIN(indexed address,indexed address,uint256)'
          handler: handleJoinPool
        - event: 'LOG_EXIT(indexed address,indexed address,uint256)'
          handler: handleExitPool
        - event: >-
            LOG_SWAP(indexed address,indexed address,indexed
            address,uint256,uint256)
          handler: handleSwap
        - event: 'Transfer(indexed address,indexed address,uint256)'
          handler: handleTransfer
      file:
        /: /ipfs/QmRpuRtWKVF7Hp6auTkCnccQu8B83dgsEbwNrjFGMwGmJ5
      kind: ethereum/events
      language: wasm/assemblyscript
    name: Pool
    network: mainnet
    source:
      abi: Pool
  - kind: ethereum/contract
    mapping:
      abis:
        - file:
            /: /ipfs/QmSdM7LmKJmQWQ1hB8cRpRHzSX5y9pJ4gLzn96cRwHGsHS
          name: DataToken
      apiVersion: 0.0.4
      entities:
        - DataToken
        - DatatokenFactory
      eventHandlers:
        - event: 'Transfer(indexed address,indexed address,uint256)'
          handler: handleTransfer
        - event: >-
            OrderStarted(indexed address,indexed
            address,uint256,uint256,uint256,indexed address,uint256)
          handler: handleOrderStarted
      file:
        /: /ipfs/QmTdnukhWti63JtbTzZH1NQbLLunuvEgC2vMRRfqWeaNxZ
      kind: ethereum/events
      language: wasm/assemblyscript
    name: DataToken
    network: mainnet
    source:
      abi: DataToken
```
