### ISSUE TITLE
graph-cli >=0.30.0 dataSourceName is undefined in `init` command

### ISSUE THREAD

**Issue by dimitrovmaksim** [graphprotocol/graph-cli#899]
I can see that this PR https://github.com/graphprotocol/graph-cli/pull/888 has introduced a new param `dataSourceName` to `initSubgraphFromContract` and `generateScaffold` functions in the `init` command, but i can't see where `dataSourceName` comes from and where it is being set in the `init.js` file, and currently when generating a new subgraph, it results in the name of the dataSource to be `undefined` in the subgraph.yaml (also affects `codegen`)

```
specVersion: 0.0.4
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: undefined
    network: mainnet
    source:
      address: "0x2E645469f354BB4F5c8a05B3b30A929361cf77eC"
      abi: Gravity
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.5
      language: wasm/assemblyscript
      entities:
        - NewGravatar
        - UpdatedGravatar
      abis:
        - name: Gravity
          file: ./abis/Gravity.json
      eventHandlers:
        - event: NewGravatar(uint256,address,string,string)
          handler: handleNewGravatar
        - event: UpdatedGravatar(uint256,address,string,string)
          handler: handleUpdatedGravatar
      file: ./src/gravity.ts
```
