### ISSUE TITLE
It won't recognize the new `receipt: true` in subgraph.yaml

### ISSUE THREAD

**Issue by jurgenwerk** [graphprotocol/graph-cli#924]
I'm trying to get the [transaction receipts](https://thegraph.com/docs/en/developer/create-subgraph-hosted/#transaction-receipts-in-event-handlers) working but I'm getting errors about an unrecognized key.

I'm on:
```
"@graphprotocol/graph-cli": "0.32.0",
"@graphprotocol/graph-ts": "0.27.0",
```

My subgraph.yml looks like this:

```
### This is an auto generated file, please do not edit this file ###
### network: gnosis

specVersion: 0.0.5
schema:
  file: ./schema.graphql

dataSources:
  - kind: ethereum/contract
    name: PrepaidCard
    network: xdai
    source:
      address: ...
      abi: PrepaidCardManager
      startBlock: 17265698
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        ...
      abis:
        ...
      eventHandlers:
        - event: CreatePrepaidCard(address,address,address,address,uint256,uint256,uint256,string)
          handler: handleCreatePrepaidCard
          receipt: true
```
          
And when trying to deploy the graph using `graph deploy local-subgraph --debug-fork QmWawe5A2qv5g9gJE3djFCkvRCqBvt8f6xcJR3JRB64wLu --ipfs http://localhost:5001 --node http://localhost:8020`, I get the following error:
     
```
     Error: Error in subgraph.yaml:

  Path: dataSources > 0 > mapping > eventHandlers > 0
  Unexpected key in map: receipt
  ```
  
  Any ideas?
