### ISSUE TITLE
Support more than one address per source

### ISSUE THREAD

**Issue by KholdStare** [graphprotocol/graph-cli#985]
The `subgraph.yaml` schema is very poorly documented. The only place I see is here: https://thegraph.academy/developers/defining-a-subgraph/ which is a tutorial. There needs to be a dedicated reference-style document describing the schema of this file.

In particular we are trying to figure out how to define several `dataSources.source` values for the same ABI/mapping. We have several contracts that have the same event ABI that we want to listen to.

```yaml
# ...
dataSources:
  - kind: ethereum/contract
    name: Gravity
    network: mainnet
    source: # support several sources here
      address: '0x2E645469f354BB4F5c8a05B3b30A929361cf77eC'
      abi: Gravity
      startBlock: 6175244
    mapping:
# ...
```

Otherwise we have to duplicate a lot of code in `subgraph.yaml` just to listen to one more address.
